language: ruby
rvm: '2.5.0'

services:
  - postgresql

install:
  - bundle install

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
