development:
  adapter: postgresql
  encoding: unicode
  database: chitter
  pool: 2
  username: student
  password:

production :
  adapter: postgresql
  encoding: unicode
  database: chitter
  pool: 2
  username: student
  password:
